export enum EnumPrioridadeTramitacao {
  SEM_PRIORIDADE = "SEM_PRIORIDADE",
  PESSOA_COM_IDADE_SUPERIOR_A_60_ANOS = "PESSOA_COM_IDADE_SUPERIOR_A_60_ANOS",
  PESSOA_COM_NECESSIDADES_ESPECIAIS_OU_DOENCA_GRAVE = "PESSOA_COM_NECESSIDADES_ESPECIAIS_OU_DOENCA_GRAVE"
}
